name: Build and Deploy package
on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Build package (live)
      if: startsWith(github.ref, 'refs/heads/')
      uses: pguyot/arm-runner-action@v2
      env:
        ENV_VERSION: 0
      with:
        image_additional_mb: 1024
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a7
        cpu_info: cpuinfo/raspberrypi_4b
        copy_artifact_path: uconsole-sleep.deb
        commands: |
          ./make_uconsole-sleep_package.sh
          pwd
          ls -la
    - name: Upload package to release (live)
      if: startsWith(github.ref, 'refs/heads/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.REPO_TOKEN }}
        file: uconsole-sleep.deb
        asset_name: uconsole-sleep-live.deb
        tag: live
        overwrite: true
        prerelease: true
    - name: Build package
      if: startsWith(github.ref, 'refs/tags/')
      uses: pguyot/arm-runner-action@v2
      env:
        ENV_VERSION: ${{ github.ref }}
      with:
        image_additional_mb: 1024
        base_image: raspios_lite_arm64:latest
        cpu: cortex-a7
        cpu_info: cpuinfo/raspberrypi_4b
        copy_artifact_path: uconsole-sleep.deb
        commands: |
          ENV_VERSION=$(echo $ENV_VERSION | sed 's|refs/tags/v||g')
          ./make_uconsole-sleep_package.sh
          pwd
          ls -la
    - name: Upload package to release
      if: startsWith(github.ref, 'refs/tags/')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.REPO_TOKEN }}
        file: uconsole-sleep.deb
        asset_name: uconsole-sleep.deb
        tag: ${{ github.ref }}
        overwrite: true
        draft: true
