name: Build and Deploy package
on:
  push:
    tags:
      - '*'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Build package
      env:
        ENV_VERSION: ${{ github.ref }}
      run: |
        sed -i "s|ENV_VERSION|$ENV_VERSION|g" make_uconsole-sleep_package.sh
        ./make_uconsole-sleep_package.sh
        ls -la ..
        ls -la
    - name: Upload package to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.REPO_TOKEN }}
        file: uconsole-sleep.deb
        asset_name: ${{ github.ref }}
        tag: ${{ github.ref }}
        overwrite: true
        prerelease: true
